name: Release

on:
  push:
    branches:
      - main

jobs:
  Release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Release
        uses: agilecustoms/publish@main
        with:
          npm-extra-deps: conventional-changelog-conventionalcommits@9.1.0
        env:
          GH_TOKEN: ${{ secrets.GH_PUBLIC_RELEASES_TOKEN }}
