name: Test

on:
  push:
    branches:
      - feature

jobs:
  Test:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Release
        uses: agilecustoms/gha-release@feature
        with:
          AWS_ACCOUNT: ${{ vars.AWS_ACCOUNT_SHARED }}
